version: 2

linters:
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - fmt.Print
        - fmt.Printf
        - fmt.Println
